name: Code Review with RebotAI

on:
  issue_comment:
    types: [created]

jobs:
  code_review:
    if: >
      github.event.issue.pull_request != null &&
      contains(github.event.comment.body, '/review')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Use RebotAI action
        uses: fiqryq/rebotai@v1.0.7
        with:
          gh-token: ${{ secrets.GH_TOKEN }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
